version: "3.8"

services:
  app:
    image: rfqma/rfqma-v1:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3011:3000"
    restart: always
